name: Build Topaz Mobile APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v4

      - name: Instalar Android SDK
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Preparar projeto Topaz
        run: |
          rm -rf temp
          unzip -q TopazMobile_v1.2.zip -d temp

          cp -r temp/TopazMobileFinal/. .

          rm -rf temp

      - name: Garantir tema Android
        run: |
          if [ -f app/src/main/res/values/styles.xml ]; then
            sed -i 's/parent="Theme.AppCompat.NoActionBar"/parent="android:style\/Theme.Material.NoActionBar"/' app/src/main/res/values/styles.xml
          fi

      - name: Gerar APK Debug
        run: |
          gradle :app:assembleDebug --no-daemon

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: TopazMobile-APK
          path: app/build/outputs/apk/debug/*.apk
